package com.zzw.guanglan.socket;

public interface EventBusTag {
    String TAG_RECIVE_MSG = "TAG_RECIVE_MSG";
    String TAG_SEND_MSG = "TAG_SEND_MSG";


    String GET_DEVICE_SERIAL_NUMBER = "GET_DEVICE_SERIAL_NUMBER";
    String SEND_TEST_ARGS_AND_START_TEST = "SEND_TEST_ARGS_AND_START_TEST";
    String SEND_TEST_ARGS_AND_STOP_TEST = "SEND_TEST_ARGS_AND_STOP_TEST";
    String GET_SOR_FILE = "GET_SOR_FILE";
    String SEND_RE = "SEND_RE";
    String SEND_HEART = "SEND_HEART";
    String RE_HEART = "RE_HEART";

    String SOR_RECIVE_SUCCESS = "SOR_RECIVE_SUCCESS";
    String SOR_RECIVE_FAIL = "SOR_RECIVE_FAIL";
    String SOCKET_CONN_STATUS_CHANGE = "SOCKET_CONN_STATUS_CHANGE";
    String RECIVE_DEVICE_SERIAL_NUMBER = "RECIVE_DEVICE_SERIAL_NUMBER";

}
